dataloader:
  dataset_file: Superstore.csv
  dataset_name: ishanshrivastava28/superstore-sales

columns:
  piechart:
    - "Ship Date"
    - "Ship Mode"
    - "Category"
    - "Sub-Category"
    - "Sales"
  barplot:
    - "Order Date"
    - "Category"
    - "Sub-Category"
    - "Sales"
    - "Profit"
  geomap:
    - "Order Date"
    - "Country"
    - "State"
    - "Postal Code"
    - "Category"
    - "Sub-Category"
    - "Sales"
    - "Profit"
  linechart:
    - "Order Date"
    - "Category"
    - "Sales"
  bentoboxes:
    - stu
    - vwx
